FROM ubuntu

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    wget \
    vim \
    cmake \
    python2.7 \
    python3.2
 
RUN apt-get update && apt-get install -y \
    libboost-all-dev

RUN apt-get update && apt-get install -y telnet

RUN apt-get update && apt-get install -y \
    libblkid-dev e2fslibs-dev libaudit-dev
